name: Basic CI

# Cuándo se ejecuta: en cada push y pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Descarga tu código
    - uses: actions/checkout@v4
    
    # 2. Configura Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    # 3. Instala dependencias básicas
    - name: Install basic tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    # 4. Validación de requirements.txt
    - name: Validate requirements.txt
      run: |
        if [ -f requirements.txt ]; then
          echo "📋 Found requirements.txt, validating..."
          echo "📦 Installing dependencies from requirements.txt"
          pip install -r requirements.txt
          echo "✅ All dependencies installed successfully!"
          echo "📊 Installed packages:"
          pip list
        else
          echo "⚠️  No requirements.txt found"
          echo "Consider creating one with: pip freeze > requirements.txt"
        fi
    
    # 4. Linting básico - detecta errores de sintaxis
    - name: Lint with flake8
      run: |
        # Para por errores de sintaxis y variables no definidas
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Warnings menos críticos (opcional)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # 5. Verificación básica - tu script principal funciona
    - name: Basic smoke test
      run: |
        # Verifica que Python puede importar tus módulos principales
        python -c "import sys; print('Python version:', sys.version)"
        # Si tienes un main.py, verifica que no explota al importarse
        if [ -f main.py ]; then python -c "import main; print('main.py imports successfully')"; fi